services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis:/data
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: 64M
    environment:
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=everysec
    command: redis-server --appendonly yes --appendfsync everysec
  hyper-link-stretch:
    image: lbty/hyper-link-stretch:latest
    #机器内存比较小可以使用下面这个
    #image:lbty/hyper-link-stretch:ibm-semeru
    restart: always
    command: java -Xmx128m -Xms64m -jar HyperLinkStretch.jar
    ports:
      - "8080:8080"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 128M
