version: "1.0"
services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis:/data
  hyper-link-stretch:
    image: lbty/hyper-link-stretch:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis
